fix: rejig auth page logic
freeCodeCamp/auth0-templates pull request #23
Opened 2021-06-25 18:04 UTC by raisedadead

2021-06-25 18:08 UTC, nhcarrigan approved these changes
Quick QA on staging and looks good to me.

2021-06-25 18:39 UTC, raisedadead commented
Sorry about the noise, I went ahead and unified this even further so we can deploy the same code on both staging and production tenants.

2021-06-25 19:47 UTC, QuincyLarson requested changes
This is almost perfect. Just a couple quick edits for you.

2021-06-25 19:47 UTC, QuincyLarson commented on pages/login.html
> +                    Submit the sign in code and login</button>
Could you update this to say: "Submit the sign in code and sign in to freeCodeCamp"

By the way, "login" is a noun. "log in" is a verb. 

Since "sign in" is more common than "log in" we should just stick with that expression.

2021-06-25 19:47 UTC, QuincyLarson commented on emails/passwordless-login-code.html
> +              minutes.</p>
Does this indeed expire after 5 minutes? For the sign in code, it expires after 15 minutes. So I just wanted to make sure these were in fact different time limits.

2021-06-26 06:52 UTC, raisedadead commented on pages/login.html
> +                    Submit the sign in code and login</button>
Thanks, I have updated your comment to make it a suggestion, you get the credit for the commit.

2021-06-26 07:04 UTC, raisedadead commented on emails/passwordless-login-code.html
> +              minutes.</p>
That duration is correct technically.

However, we do not use this whole section of the template (a lot of it actually). We could do some optimising and remove the parts we do not use and need - but I would do that audit off of this PR.

2021-06-26 07:05 UTC, merged